[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/tools/**", "*/plugins/**", "*/custom/**", "*/lib/**", "*/*.sh"]
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/k"]
    type = "archive"
    url = "https://github.com/supercrabtree/k/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".xmonad/xmonad"]
    type = "archive"
    url = "https://github.com/xmonad/xmonad/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".xmonad/xmonad-contrib"]
    type = "archive"
    url = "https://github.com/xmonad/xmonad-contrib/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
['.local/share/nvim/site/pack/plugins/start/chezmoi.vim']
    type = "archive"
    url = "https://github.com/alker0/chezmoi.vim/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
['.local/share/nvim/site/pack/plugins/start/packer.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/wbthomason/packer.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-web-devicons']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/kyazdani42/nvim-web-devicons/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/plenary.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/nvim-lua/plenary.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/Comment.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/numToStr/Comment.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-autopairs']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/windwp/nvim-autopairs/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-colorizer.lua']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/norcalli/nvim-colorizer.lua/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/indent-blankline.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/lukas-reineke/indent-blankline.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/vim-easy-align']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/junegunn/vim-easy-align/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/vim-kitty']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/fladson/vim-kitty/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-tree.lua']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/kyazdani42/nvim-tree.lua/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/lualine.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/nvim-lualine/lualine.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/gitsigns.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/lewis6991/gitsigns.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/neogit']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/TimUntersberger/neogit/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/tokyonight.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/folke/tokyonight.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-lsp-installer']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/williamboman/nvim-lsp-installer/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-lspconfig']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/neovim/nvim-lspconfig/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-cmp']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/nvim-cmp/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/lspkind.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/onsails/lspkind.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/LuaSnip']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/L3MON4D3/LuaSnip/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/symbols-outline.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/simrat39/symbols-outline.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/lspsaga.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/glepnir/lspsaga.nvim/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-treesitter']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/nvim-treesitter/nvim-treesitter/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/nvim-ts-rainbow']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/p00f/nvim-ts-rainbow/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp_luasnip']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/saadparwaiz1/cmp_luasnip/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-buffer']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/cmp-buffer/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-calc']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/cmp-calc/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-digraphs']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/dmitmel/cmp-digraphs/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-nvim-lsp']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/cmp-nvim-lsp/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-nvim-lsp-document-symbol']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/cmp-nvim-lsp-document-symbol/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-nvim-lsp-signature-help']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/cmp-nvim-lsp-signature-help/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-path']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/cmp-path/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-cmdline']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/cmp-cmdline/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-cmdline-history']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/dmitmel/cmp-cmdline-history/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-greek']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/max397574/cmp-greek/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-latex-symbols']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/kdheepak/cmp-latex-symbols/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/cmp-nvim-lua']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/hrsh7th/cmp-nvim-lua/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/friendly-snippets']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/rafamadriz/friendly-snippets/archive/master.tar.gz"
['.local/share/nvim/site/pack/plugins/start/LuaSnip-snippets.nvim']
    type = "archive"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    url = "https://github.com/molleweide/LuaSnip-snippets.nvim/archive/master.tar.gz"
[".lang/gprolog"]
    type = "archive"
    url = "https://github.com/didoudiaz/gprolog/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "840h"
[".lang/erlnag"]
    type = "archive"
    url = "https://github.com/erlang/otp/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "840h"
[".lang/elixir"]
    type = "archive"
    url = "https://github.com/elixir-lang/elixir/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "840h"
[".lang/clojure"]
    type = "archive"
    url = "https://github.com/clojure/clojure/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "840h"
[".lang/opam"]
    type = "archive"
    url = "https://github.com/ocaml/opam/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "840h"
[".lang/tectonic"]
    type = "git-repo"
    url = "https://github.com/tectonic-typesetting/tectonic.git"
    stripComponents = 1
    args = ["--recursive"]
    refreshPeriod = "840h"
[".lang/julia"]
    type = "archive"
    url = "https://github.com/JuliaLang/julia/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "840h"
[".lang/rebar3"]
    type = "archive"
    url = "https://github.com/erlang/rebar3/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "840h"
[".lang/kotlin"]
    type = "archive"
    url = "https://github.com/JetBrains/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "840h"
