# vim:fileencoding=utf-8:foldmethod=marker

#fonts
font_family       JetBrainsMono Nerd Font Mono
bold_font         JetBrains Mono Bold Nerd Font Complete Mono
italic_font       JetBrains Mono Italic Nerd Font Complete Mono
bold_italic_font  JetBrains Mono Bold Nerd Font Complete Mono
font_size 14.0
#font_features none

cursor none
cursor_shape block
mouse_hide_wait -1
url_style dotted
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
select_by_word_characters @-./_~?&=%+#
enable_audio_bell no
visual_bell_duration 0.0
enabled_layouts Fat, Tall, Grid

window_border_width 1pt
draw_minimal_borders yes
window_margin_width 0
single_window_margin_width -1
window_padding_width 0
placement_strategy center

background_opacity 0.6

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard

#color
background #24283b
foreground #c0caf5
selection_background none
selection_foreground none
url_color #73daca
cursor #c0caf5
tab_bar_background none
tab_bar_margin_color none
active_border_color #00ff00
inactive_border_color #cccccc
bell_border_color #ff5a00

active_tab_background #7aa2f7
active_tab_foreground #1f2335
inactive_tab_background #292e42
inactive_tab_foreground #545c7e
tab_bar_background #1D202F

color0 #1D202F
color1 #f7768e
color2 #9ece6a
color3 #e0af68
color4 #7aa2f7
color5 #bb9af7
color6 #7dcfff
color7 #a9b1d6
color8 #414868
color9 #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5
color16 #ff9e64
color17 #db4b4b
mark1_foreground black
mark1_background #98d3cb
mark2_foreground black
mark2_background #f2dcd3
mark3_foreground black
mark3_background #f274bc
