local enum = {
    lsp = {
        "bashls",
        "clangd",
        "clojure_lsp",
        "cmake",
        "cssls",
        "elixirls",
        "elmls",
        "erlangls",
        "eslint",
        "gopls",
        "hls",
        "html",
        "jedi_language_server",
        "jsonls",
        "julials",
        "kotlin_language_server",
        "ltex",
        "metals",
        "omnisharp",
        "ocamllsp",
        "pylsp",
        "pyright",
        "rust_analyzer",
        "sorbet",
        "sumneko_lua",
        "taplo",
        "texlab",
        "tsserver",
        "vimls",
        "yamlls",
    },
    symbol = {
        type   = {
            Text          = '',
            Method        = '𝛌',
            Function      = '𝛌',
            Constructor   = '',
            Field         = '',
            Variable      = '',
            Class         = '',
            Interface     = '',
            Property      = "",
            Module        = '',
            Unit          = '',
            Value         = '',
            Enum          = '',
            Keyword       = '',
            Snippet       = '',
            Color         = "",
            File          = '',
            Reference     = '',
            Folder        = '',
            EnumMember    = '',
            Constant      = '',
            Struct        = '',
            Event         = '',
            Operator      = '',
            TypeParameter = '𝐓',
        },
        folder = {
            arrow_closed = "",
            arrow_open = "",
            default = "",
            open = "",
            empty = "",
            empty_open = "",
            symlink = "",
            symlink_open = "",
        },
        git    = {
            unstaged = "",
            staged = "",
            unmerged = "",
            renamed = "",
            untracked = "",
            deleted = "",
            ignored = "",
        },
        status = {
            hint = "",
            info = "",
            warning = "",
            error = "",
            default = "",
            symlink = "",
            symlink_arrow = "",

        },
        glyps = {
            component_separators_left = '',
            component_separators_right = '',
            section_separators_left = '',
            section_separators_right = '',
            corner = "└ ",
            edge = "│ ",
            item = "│ ",
        }
    },
    colors = {
        black   = "#242424",
        deep    = "#636363",
        ash     = "#989898",
        light   = "#d1d1d1",
        white   = "#F9F9F9",
        red     = "#A34451",
        brown   = "#905427",
        green   = "#00734D",
        blue    = "#006EA3",
        puple   = "#884d8b",
        magenta = "#ff85a8",
        orange  = "#FFAF43",
        yellow  = "#FFCA0F",
        teal    = "#3eef73",
        cyan    = "#00F1FF",
        pale    = "#a4c6ff",
    }
}
return enum
