local opts = { noremap = true, silent = true }
vim.keymap.set("n", "[d", vim.diagnostic.goto_next, opts)
vim.keymap.set("n", "]d", vim.diagnostic.goto_prev, opts)
vim.keymap.set('n', '<F2>', '<Plug>(EasyAlign)', opts)
vim.keymap.set('x', '<F2>', '<Plug>(EasyAlign)', opts)
vim.keymap.set('n', '<F3>', ':SymbolsOutline<CR>', opts)
vim.keymap.set('n', '<s-v>', '<c-v>', opts)
vim.keymap.set('n', '<c-s>', ':wq<CR>', opts)
vim.keymap.set('n', '<F5>', ':w<CR>', opts)
vim.keymap.set('n', '<c-q>', ':qa<CR>', opts)
vim.keymap.set('n', 'gj', 'j', opts)
vim.keymap.set('n', 'gk', 'k', opts)
vim.keymap.set('n', 'j', 'gj', opts)
vim.keymap.set('n', 'k', 'gk', opts)
vim.keymap.set('n', '<space>f', function() vim.lsp.buf.format { async = true } end, opts)
vim.keymap.set("n", "<space>a", vim.lsp.buf.code_action, opts)
vim.keymap.set("n", "<space>n", vim.lsp.buf.rename, opts)
vim.keymap.set("n", "<space>h", vim.lsp.buf.hover, opts)
vim.keymap.set("n", "<space>s", vim.lsp.buf.signature_help, opts)
vim.keymap.set("n", "<space>d", vim.lsp.buf.definition, opts)
vim.keymap.set('n', '<space>D', vim.lsp.buf.declaration, opts)
vim.keymap.set("n", "<space>i", vim.lsp.buf.implementation, opts)
vim.keymap.set('n', '<space>t', vim.lsp.buf.type_definition, opts)
vim.keymap.set('n', '<space>r', vim.lsp.buf.references, opts)
vim.keymap.set('n', '<M-v>', ':NvimTreeToggle<CR>', opts)
vim.keymap.set('n', '<M-g>', ':Neogit<CR>', opts)
vim.keymap.set('n', '<M-b>', ':!brave %<CR>', opts)
vim.keymap.set('n', '<Leader>e', ':lua require("expand_expr").expand()<CR>', opts)

-- place this in one of your configuration file(s)
local hop = require('hop')
local directions = require('hop.hint').HintDirection
hop.setup()
vim.keymap.set('', 'f', function()
	hop.hint_char2({ direction = directions.AFTER_CURSOR })
end, { remap = true })
vim.keymap.set('', 'F', function()
	hop.hint_char2({ direction = directions.BEFORE_CURSOR })
end, { remap = true })
vim.keymap.set('', 't', function()
	hop.hint_char2({ direction = directions.AFTER_CURSOR, hint_offset = -1 })
end, { remap = true })
vim.keymap.set('', 'T', function()
	hop.hint_char2({ direction = directions.BEFORE_CURSOR, hint_offset = 1 })
end, { remap = true })
vim.keymap.set('n', 'gv', ':HopVertical<CR>',opts)
vim.keymap.set('n', 'gp', ':HopPattern<CR>',opts)
vim.keymap.set('n', 'gw', ':HopWord<CR>',opts)
